⚡️fix: signup 페이지 pr 리뷰 반영, stpe3 모달 추가
P1Z7/frontend pull request #15
Opened 2024-01-26 17:57 UTC by kde98892

## ✏️ 변경사항
- [X] signup 페이지 pr 리뷰 반영
  - 컨벤션 적용
  - 타입 수정
  - step3 아티스트 각 카드 checked 정보 가져오는 로직 수정 (Dom 접근 x)
- [X] 모달 연결
- [X] 체크된 아티스트 UI peer 안써도 되도록 로직 변경

2024-01-26 18:29 UTC, naya-h2 approved these changes

2024-01-26 18:29 UTC, naya-h2 commented on app/(route)/signup/_components/step/ProfileInfo.tsx
> +        hint="n/10"
이거 hint 말고 maxLength로 설정해주면 하늘님이 n도 바뀌게 해주셨어용 ㅎㅎ

2024-01-26 18:29 UTC, naya-h2 commented on app/(route)/signup/page.tsx
> +const STEPS: StepNameType[] = ["계정 정보", "프로필 정보", "아티스트 선택"];
엇 step도 타입 지정해두셧네요 ?!!???

2024-01-26 18:29 UTC, naya-h2 commented on app/(route)/signup/page.tsx
> +  const { Funnel, Step, setStep, currentStep } = useFunnel(STEPS[0]);
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ아 대문자로 바꾼거 귀엽다 ^_^

2024-01-26 18:29 UTC, naya-h2 commented on app/(route)/signup/_components/step/MyArtistsInfo.tsx
> +      {modal === "req_artist" && <ReqNewArtistModal closeModal={closeModal} />}
모달생겼당

2024-01-27 04:30 UTC, kde98892 commented on app/(route)/signup/_components/step/ProfileInfo.tsx
> +        hint="n/10"
헉 그냥 조건 추가인 줄 알았는데........!! 완전 감사합니닷

2024-01-27 04:30 UTC, kde98892 commented on app/(route)/signup/_components/step/MyArtistsInfo.tsx
> +      {modal === "req_artist" && <ReqNewArtistModal closeModal={closeModal} />}
사용법 왕쉽다 모달;; 누가 만들었대?

2024-01-27 04:30 UTC, kde98892 commented on app/(route)/signup/page.tsx
> +const STEPS: StepNameType[] = ["계정 정보", "프로필 정보", "아티스트 선택"];
하늘님의 추천으로...!! 근데 useFunnel에도 이 타입 지정 중이라 post step도 타입에 추가해야 타입에러 안 날 것 같아용,,

2024-01-27 04:30 UTC, kde98892 commented on app/(route)/signup/page.tsx
> +  const { Funnel, Step, setStep, currentStep } = useFunnel(STEPS[0]);
ㅋㅋㅋㅋㅋㅋㅋ희희,,

2024-01-27 06:18 UTC, han-kimm commented on app/(route)/signup/_components/step/ProfileInfo.tsx
> +        hint="n/10"
@kde98892 맞아요 hotfix라서 제대로 설명이 안되었었네요!!
error메시지가 우선적으로 출력되고, 에러가 없으면 hint 나오구요.

hint로 글자수를 처리하는게 맞지 않다고 생각들어서 maxLength 처리를 했습니다.
react hook form에서 rules 정할때도 maxLength써서 비슷하게 쓰려고했어요!
디폴트값 정할 때 maxLength도 정해서

```ts
const SIGNUP_DEFAULT = {
  ... // defaultValues 설정
  rules : {
  maxLength: 3
  }
}

<InputText maxLength={SIGNUP_DEFAULT.rules.maxLength}>
```

이런 식으로 쓰면 좋을거같아요

2024-01-27 06:21 UTC, gw-lim approved these changes

2024-01-27 06:21 UTC, gw-lim commented on app/(route)/signup/page.tsx
> +const STEPS: StepNameType[] = ["계정 정보", "프로필 정보", "아티스트 선택"];
요거 signup 페이지에서면 쓰는 타입이면 `SigninStepNameType` 같이 명시적으로 하면 좋을 것 같은데 너무 길어질까요..??

2024-01-27 06:21 UTC, gw-lim commented on app/(route)/signup/page.tsx
>        </GenericForm>
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 좋다

2024-01-27 06:24 UTC, Nico1eKim reviewed
경찰 출동~~

2024-01-27 06:24 UTC, Nico1eKim commented on app/(route)/signup/_components/step/AccountInfo.tsx
>  export const AccountInfo = ({ onNext }: { onNext: () => void }) => {
헉~~ 컴포넌트 export는 바로하지 말구 밑에서 해주세용~

2024-01-27 06:24 UTC, Nico1eKim commented on app/(route)/signup/_components/step/MyArtistsInfo.tsx
> +    setIsChecked(!isChecked);
이거 안좋은 형식 아닌가요..!?
prev로 해주는게 좋을거가타용ㅇ

2024-01-27 06:24 UTC, Nico1eKim commented on app/(route)/signup/page.tsx
> +    }
아니 저 router.push 쓰지 말라고 오류띄우던데 다은님은 오류 없었나요..!?

2024-01-27 07:06 UTC, han-kimm requested changes
다은님... 타입스크립트 어려우시면 디스코드에서 다시 만나요

2024-01-27 07:06 UTC, han-kimm commented on app/_hooks/useFunnel.tsx
> +export const useFunnel = (defaultStep: StepNameType) => {
[ 새로운 방식 적용과 함께 얻어지는 타입 안정성 ]
배열을 받아옴으로써, 해당 배열 안의 모든 요소들이 어떤 문자열 값인지 알 수 있게 Type Generic을 적용했습니다!
이를테면 `defaultStepArray`가 ["프로필 설정", "아티스트 선정"] 이라면 제네릭을 통해서 `"프로필 설정"`, `"아티스트 선정"`이라는 타입을 추론할 수 있습니다!
이렇게 추론된 타입을 `StepType`과 `FunnelType`에도 적용하여 Step 컴포넌트의 name Prop이 자동완성 되게 만들 수 있습니다. 해당 자동완성 값은 DefaultStepArray의 값에 따라서 달라집니다!

![image](https://github.com/P1Z7/frontend/assets/78120157/484edfe4-851a-4b21-b915-4b43f82d1895)

2024-01-27 07:06 UTC, han-kimm commented on app/_hooks/useFunnel.tsx
> +export const useFunnel = (defaultStep: StepNameType) => {
[ defaultStepArray를 변수에 저장해서 넣고 싶다면? ]
`useFunnel([""])` 형태로 바로 배열을 작성해서 넣어줄 수 있지만, 해당 페이지에서 필요한 Step들을 상수로 관리한다면 변수에 저장하게 되겠죠?

이 경우에는 두 가지 방식을 이용해서 배열을 변수에 할당할 수 있습니다.
1. `StepNameType[]`을 이용해서 변수를 선언할 때부터 필요한 문자열값만 배열에 담기
2. 배열을 선언하고 `as const`를 이용하기

![image](https://github.com/P1Z7/frontend/assets/78120157/9ded84ad-5a36-4db6-aecc-81d3769c99f3)

2024-01-27 08:20 UTC, kde98892 commented on app/(route)/signup/_components/step/AccountInfo.tsx
>  export const AccountInfo = ({ onNext }: { onNext: () => void }) => {
악 고멘나사이..

2024-01-27 08:20 UTC, kde98892 commented on app/(route)/signup/_components/step/AccountInfo.tsx
>          name="passwordCh"
일부러 Ch로 했어요! 체크 다 적으면 너무 길어서 어떻게 할까 고민하다가 이전 프로젝트 코드 반영~~ 구린가요?

2024-01-27 08:20 UTC, kde98892 commented on app/(route)/signup/_components/step/ProfileInfo.tsx
> +        hint="n/10"
으으으음 고민되는 지점이
1) DEFAULT_VALUES 는 인풋에 들어가는 초기값을 설정해 주기 위한 변수인데, 의도와 부합하지 않지 않을까
2) 나머지 rule은 모두 utils 파일에서 관리해서 넣어주고 있는데 닉네임 maxLength만 따로 있으면 이상하지 않을까?(아래처럼)
인데요.. 어떻게 생각하시나요 ? 저는 그냥 사용처에서 10 넣는 것도 나쁘지 않은 것 같아서욥
`rules={{ required: ERROR_MESSAGES.password.passwordField, pattern: { value: REG_EXP.CHECK_PASSWORD, message: ERROR_MESSAGES.password.passwordPattern } }}`

2024-01-27 08:20 UTC, kde98892 commented on app/(route)/signup/page.tsx
> +const STEPS: StepNameType[] = ["계정 정보", "프로필 정보", "아티스트 선택"];
수정하겠습니다💪

2024-01-27 08:20 UTC, kde98892 commented on app/(route)/signup/page.tsx
> +    }
import { useRouter } from "next/navigation"; 이걸로 사용하셨나요..? "next/router 이면 아마 오류날거에요!

2024-01-27 08:20 UTC, kde98892 commented on app/(route)/signup/page.tsx
>        </GenericForm>
ㅋㅋㅋㅋㅋㅋㅋ큐ㅠ

2024-01-27 08:20 UTC, kde98892 commented on app/_hooks/useFunnel.tsx
> +export const useFunnel = (defaultStep: StepNameType) => {
타입 수정해서 다시 pr 올리겠습니다!! 확실히 확장성을 고려했을 때도 훨씬 좋은 방식인 것 같아요 제네릭 고수가 되는 길은 정말 멀고도 험난,,

2024-01-28 05:09 UTC, han-kimm approved these changes

2024-01-28 07:11 UTC, Nico1eKim commented on app/(route)/signup/page.tsx
> +    }
세상에나 저 그래서 모든 router.push를 href로 썼던거같은데......... navigation으로 쓰면 되는군아....ㅋ..ㅋ.ㅋ.ㅋ.ㅋ.

2024-01-28 13:55 UTC, merged