✨ feat: /mypage 행사 탭 구현
P1Z7/frontend pull request #18
Opened 2024-01-28 16:52 UTC by Nico1eKim

## ✏️ 변경사항

- [ ] react-calendar를 이용해서 /mypage의 행사 탭을 구현했습니다
- [ ] 아무날짜도 선택하지 않은 상태이면 모든 행사가 보이도록 했습니다
- [ ] 특정 날짜를 선택하면 해당 날짜의 모든 행사가 보이도록 했습니다

## 📷 스크린샷

https://github.com/P1Z7/frontend/assets/102296721/9de46f5b-96ba-46aa-8a69-6520111a351b

## 🎸 기타

- 부족한 점이 많은 코드라서 신랄한 리뷰 대환영입니다....
- 컨플릭트가 크게 날 것 같은 코드는 일부러 push하지 않았습니당 (제 이전 코드가 아직 머지가 안됐는데 제가 해당 파트를 건드려야 할 일이 생겨서.. 조금 건드렸는데 많은 파일에서 컨플릭트 날 것 같아서 추후 수정할게용)

2024-01-28 17:10 UTC, Nico1eKim commented on app/(route)/mypage/_components/EventCalendar.tsx
> +  // new Date(2024, 0, 28) -> 이런식으로 작성하면 해결 가능..
이부분 진심 미스테리입니다.... 구글링해도 나오는 내용이 없고..ㅠㅠㅠ
날짜를 받아올 때 Date로 받아온다면 지금 제가 하는 방식으로 해도 상관 없지만 string으로 받아오게 된다면 큰 문제 발생..ㅠㅠ

2024-01-28 17:10 UTC, Nico1eKim commented on app/(route)/mypage/_components/EventCalendar.tsx
> +  };
이부분도 풀리지 않는 의문...
계속 onChange에서 value의 타입은 Value여야 한다는 오류가 나는데 Value라는 타입이 도대체 뭔지 알 수가 없어서 any로 설정했습니다... sos...

2024-01-29 09:44 UTC, han-kimm requested changes
너무고생많으셨어요
라이브러리가 감춰놓은 비밀때문에 고생이 많네요..

2024-01-29 09:44 UTC, han-kimm commented on app/(route)/mypage/_components/EventCalendar.tsx
> +      <Calendar onChange={handleClickToday} value={date} tileContent={tileContent} />
`locale="kr"` 추가해주세요.
이 프롭 없으면 SSR일 때, 언어가 영어로 렌더링되고,
CSR일때 한국어로 렌더링되어서 hydration 오류 납니다

2024-01-29 09:44 UTC, han-kimm commented on app/(route)/mypage/_components/EventCalendar.tsx
> +    const eventsForDate = mockData.filter((event) => new Date(event.startDate).getTime() <= date.getTime() && new Date(event.endDate).getTime() >= date.getTime());
![image](https://github.com/P1Z7/frontend/assets/78120157/6b31fd21-1985-4150-a2c2-31e957a5e496)

2024-01-29 09:44 UTC, han-kimm commented on app/(route)/mypage/_components/EventCalendar.tsx
> +    const eventsForDate = mockData.filter((event) => new Date(event.startDate).getTime() <= date.getTime() && new Date(event.endDate).getTime() >= date.getTime());
![image](https://github.com/P1Z7/frontend/assets/78120157/981606e8-d069-495e-9a25-f99f22688316)

2024-01-29 09:44 UTC, han-kimm commented on app/(route)/mypage/_components/EventCalendar.tsx
> +    const eventsForDate = mockData.filter((event) => new Date(event.startDate).getTime() <= date.getTime() && new Date(event.endDate).getTime() >= date.getTime());
[시작일이 하루 밀리는 이유]
`new Date("2024-01-25")`의 리턴값은 UTC(GMT) 기준 0시인데, 유저의 OS 시간대 설정에 따라 로컬시간으로 변환되어 리턴됨. 따라서 한국시간 기준이 됨.
즉, `2024년 1월 25일 오전 09시`를 리턴함.

하지만, `Calendar`라이브러리에서 넣어주는 date 값은 한국시간 기준으로도 0시임
즉, `2024년 1월 25일 오전 0시`를 가르킴.

따라서 
`new Date(event.startDate).getTime() <= date.getTime()`의 비교 연산 값이 `false`가 되므로
25일은 시작일로 인정이 안되는 것임!

2024-01-29 09:51 UTC, han-kimm commented on app/(route)/mypage/_components/EventCalendar.tsx
> +    const eventsForDate = mockData.filter((event) => new Date(event.startDate).getTime() <= date.getTime() && new Date(event.endDate).getTime() >= date.getTime());
https://yozm.wishket.com/magazine/detail/1695/

2024-01-29 13:27 UTC, closed without merging